export const userFormConfig = [
    {
        type:"text",
        name:"name",
        label:"name",
        value:""
    },
     {
        type:"text",
        name:"email",
        label:"email",
         value:""
     },
     {
        type:"password",
        name:"password",
        label:"password",
         value:""
     },
     {
        type:"radio",
        name:"gender",
        label:"Male",
         value:"male"
     },
     {
        type:"radio",
        name:"gender",
        label:"Female",
        value:"female"
     },
     {
        type:"text",
        name:"address",
        label:"address",
        value:""
     },
     {
        type:"button",
        label:"Submit"
    }
 ]