// Part-2: Use the above data and render it in Box 1. Each student has a checkbox
// before its name and we can select multiple students at once. All the selected
// students can be moved to Box 2 by clicked on the 1st button and vice-versa for
// Box-2.
// Cisco Interview Experience | UI Developer
// Generated by Freedium 

import React from 'react';
import {useState,useEffect} from 'react';

const Cisco = () => {
    const students = [
        {
          name: "Aarav",
          marks: 92,
          registrationId: 1001,
          box:"box1",
          side:"left"
        },
        {
          name: "Priya",
          marks: 85,
          registrationId: 1002,
          box:"box1",
            side:"left"
        },
        {
          name: "Rohan",
          marks: 78,
          registrationId: 1003,
          box:"box1",
          side:"left"
        },
        {
          name: "Sneha",
          marks: 95,
          registrationId: 1004,
          box:"box1",
            side:"left"
        },
        {
          name: "Karan",
          marks: 88,
          registrationId: 1005,
          box:"box1",
          side:"left"
        },
        {
          name: "Meera",
          marks: 91,
          registrationId: 1006,
          box:"box1",
          side:"left"
        },
      ];

      const [data,setData] = useState(students);
    const [selectedBox1,setSelectedBox1] = useState([]);
    const [selectedBox2,setSelectedBox2] = useState([]);
    const [side,setSide] = useState(false);
    console.log(data,"data");
    console.log(selectedBox1,"selected1");
    console.log(selectedBox2,"selected2");

    const handleSelectedBoxOne = (checked,value) => {
        if(checked){
            setSelectedBox1((prev) =>  [...prev,value.registrationId]);
        }else{
            setSelectedBox1((prev) => prev.filter((item,i) => item != value.registrationId));
        }
        
        //   if(checked){
        //     setData(prev =>
        //         prev.map(item =>
        //           item.registrationId === value
        //             ? { ...item, box:"box2" }
        //             : item
        //         )
        //       );
        //   }
    }

    const handleSelectedBoxTwo  = (checked,value) => {
        if(checked){
            setSelectedBox2((prev) => [...prev,value.registrationId]);
        }else{
            setSelectedBox2((prev) => prev.filter((item,i) => item != value.registrationId));
        }
    }

    const handleRight = () => {
    //    setData((prev) => 
    //    prev.map((item,i) => selected.includes(item.registrationId))
    //    ?
    //    {
    //     ...item,box:"box2"
    //    }
    //    :
    //    item
    //    )
    setData(prev =>
        prev.map(item =>
          selectedBox1.includes(item.registrationId)
            ? { ...item, box: "box2" }
            : item
        )
      );
      setSelectedBox1([]);
    }
    const handleLeft = () => {
       setData((prev) => prev.map((item,i) => selectedBox2.includes(item.registrationId) ? {...item,box:"box1"} : item))
       setSelectedBox2([]);
    }
    return(
        <div>
        <h1>cisco</h1>
        <div style={{display:"flex",justifyContent:"center",alignItems:"center", gap:"10px"}}>
            <div style={{border:"1px solid green",height:"200px",width:"30%",display:"flex",justifyContent:"center",alignItems:"center",flexDirection:"column"}}>
                <h5>Box 1</h5>
{
                 data.filter((item) => item.box === "box1").map((item,i) => {
                        return(
                            <div key={item.registrationId} style={{display:"flex", gap:"10px"}}>
<input type="checkbox"  onChange={(e) => handleSelectedBoxOne(e.target.checked,item)}/><div>{item.name}</div>
</div>
                        )
                    })
                    
                }                
            </div>

             <button onClick={handleRight}>{"=>"}</button>
            <button onClick={handleLeft}>{"<="}</button>
            <div style={{border:"1px solid green",height:"200px",width:"30%",display:"flex",justifyContent:"center",alignItems:"center",flexDirection:"column"}}>
                <h5>Box 2</h5>
{
                data.filter((item) => item.box === "box2").map((item,i) => {
                        return(
                            <div key={item.registrationId}  style={{display:"flex", gap:"10px"}}>
<input type="checkbox" onChange={(e) => handleSelectedBoxTwo(e.target.checked,item)} /><div>{item?.name}</div>
</div>
                        )
                    })
                    
                }                
            </div>
        </div>
        </div>

    )
}

export default Cisco;

